[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
for = "/sitemap.xml"

[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
force = true